name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
      - name: Build
        run: ./gradlew check
      - name: Dependency check
        run: ./gradlew dependencyCheckAggregate
      - name: Test
        run: ./gradlew test